### ISSUE TITLE
Erro de ortografia 

### ISSUE THREAD

**Issue by sans-script** [sans-script/DevOps-Aulas#3]
Há erros de ortografia no readme.md 

![image](https://github.com/sans-script/DevOps-Aulas/assets/84801905/fcbcd8cb-c373-41b5-a8b9-5f57cc898bc6)

**Comment by thierrydesign** [comment]
Linha 3 do Readme foi corrigida.
![image](https://github.com/sans-script/DevOps-Aulas/assets/121128154/6da35c61-f65f-4144-88a7-93f248f3da4a)
